/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});
export const PlayerId = IDL.Principal;
export const PlayerStats = IDL.Record({
  'hasPaid' : IDL.Bool,
  'totalWon' : IDL.Nat,
  'totalSpent' : IDL.Nat,
  'totalSpins' : IDL.Nat,
});
export const Symbol = IDL.Variant({
  'bar' : IDL.Null,
  'bell' : IDL.Null,
  'orange' : IDL.Null,
  'lemon' : IDL.Null,
  'seven' : IDL.Null,
  'cherry' : IDL.Null,
});
export const ReelResult = IDL.Vec(Symbol);
export const WinRecord = IDL.Record({
  'player' : PlayerId,
  'timestamp' : IDL.Int,
  'reels' : ReelResult,
  'payout' : IDL.Nat,
});
export const SpinResult = IDL.Record({
  'won' : IDL.Bool,
  'multiplier' : IDL.Nat,
  'reels' : ReelResult,
  'payout' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminResetPool' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLeaderboard' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(PlayerId, PlayerStats))],
      ['query'],
    ),
  'getMyInfo' : IDL.Func([], [PlayerStats], ['query']),
  'getPlayerInfo' : IDL.Func([PlayerId], [PlayerStats], ['query']),
  'getPoolBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getRecentWins' : IDL.Func([], [IDL.Vec(WinRecord)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'payEntryFee' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'spin' : IDL.Func([IDL.Nat], [SpinResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  const PlayerId = IDL.Principal;
  const PlayerStats = IDL.Record({
    'hasPaid' : IDL.Bool,
    'totalWon' : IDL.Nat,
    'totalSpent' : IDL.Nat,
    'totalSpins' : IDL.Nat,
  });
  const Symbol = IDL.Variant({
    'bar' : IDL.Null,
    'bell' : IDL.Null,
    'orange' : IDL.Null,
    'lemon' : IDL.Null,
    'seven' : IDL.Null,
    'cherry' : IDL.Null,
  });
  const ReelResult = IDL.Vec(Symbol);
  const WinRecord = IDL.Record({
    'player' : PlayerId,
    'timestamp' : IDL.Int,
    'reels' : ReelResult,
    'payout' : IDL.Nat,
  });
  const SpinResult = IDL.Record({
    'won' : IDL.Bool,
    'multiplier' : IDL.Nat,
    'reels' : ReelResult,
    'payout' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminResetPool' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(PlayerId, PlayerStats))],
        ['query'],
      ),
    'getMyInfo' : IDL.Func([], [PlayerStats], ['query']),
    'getPlayerInfo' : IDL.Func([PlayerId], [PlayerStats], ['query']),
    'getPoolBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getRecentWins' : IDL.Func([], [IDL.Vec(WinRecord)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'payEntryFee' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'spin' : IDL.Func([IDL.Nat], [SpinResult], []),
  });
};

export const init = ({ IDL }) => { return []; };