/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type PlayerId = Principal;
export interface PlayerStats {
  'hasPaid' : boolean,
  'totalWon' : bigint,
  'totalSpent' : bigint,
  'totalSpins' : bigint,
}
export type ReelResult = Array<Symbol>;
export interface SpinResult {
  'won' : boolean,
  'multiplier' : bigint,
  'reels' : ReelResult,
  'payout' : bigint,
}
export type Symbol = { 'bar' : null } |
  { 'bell' : null } |
  { 'orange' : null } |
  { 'lemon' : null } |
  { 'seven' : null } |
  { 'cherry' : null };
export interface UserProfile { 'name' : string, 'email' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WinRecord {
  'player' : PlayerId,
  'timestamp' : bigint,
  'reels' : ReelResult,
  'payout' : bigint,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminResetPool' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLeaderboard' : ActorMethod<[], Array<[PlayerId, PlayerStats]>>,
  'getMyInfo' : ActorMethod<[], PlayerStats>,
  'getPlayerInfo' : ActorMethod<[PlayerId], PlayerStats>,
  'getPoolBalance' : ActorMethod<[], bigint>,
  'getRecentWins' : ActorMethod<[], Array<WinRecord>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'payEntryFee' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'spin' : ActorMethod<[bigint], SpinResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];